### ISSUE TITLE
not enough space

### ISSUE THREAD

**Issue by KaiFish** [rblack5/CodeMonkeys#1]
https://github.com/rblack5/CodeMonkeys/blob/17565166fc817374d19db445f0caa218a6c0f757/CS320_Project_Database/src/project_database/persist/DerbyDatabase.java#L462

This is going to be an issue- 40 characters isn't even a tweet. If you want to store a whole bio, you might want to make this longer or look at other data types.

**Comment by darkloor** [comment]
increased to 1000 characters for the time being
